"""empty message

Revision ID: c6c67ef19024
Revises: ba120bfdd0a9
Create Date: 2023-06-16 23:07:56.507457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6c67ef19024'
down_revision = 'ba120bfdd0a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_rooms', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('caution_deposit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.drop_column('caution_deposit')
        batch_op.drop_column('number_of_rooms')

    # ### end Alembic commands ###
